pipeline:
  build:
    image: cximage
    commands:
      - echo Run Checkmarx scan
      - pwd
      - ls -lR
      - /app/runCxConsole.sh scan -verbose -CxServer 172.17.121.135 -Projectname "CxServer\drone086" -CxUser jb@cx.com -CxPassword Poiuytrewq1@ -LocationType folder -LocationPath $(pwd)
      
