pipeline:
  build:
    image: cximage
    commands:
      - echo Run Checkmarx scan
      - pwd
      - ls -lR
      - /app/runCxConsole.sh scan -verbose -CxServer 127.0.0.1 -Projectname drone086 -CxUser jb@cx.com -CxPassword Poiuytrewq1@ -LocationType folder -LocationPath $(pwd)
      
