version: 2
jobs:
  build:
    docker:
      - image: vlecerf/checkmarx-cli-docker
    steps:
      - checkout
      - run: pwd
      - run: ls -lrt
      - run: /opt/CxConsolePlugin/runCxConsole.sh Scan -verbose -CxServer yourcheckmarxserver.com -Projectname "CxServer\yourprojectname" -CxUser yourcxusername -CxPassword yourcxpassword -LocationType folder -LocationPath $(pwd)
