version: 2
jobs:
  build:
    docker:
      - image: vlecerf/checkmarx-cli-docker
    steps:
      - checkout
      - run: /opt/CxConsolePlugin/runCxConsole.sh Scan -verbose -CxServer cxprivatecloud.checkmarx.net -Projectname "CxServer\SP\EMEA\checkmarx.com-855\testCircleCI" -CxUser julien.bruinaud@checkmarx.com -CxPassword Panaya1218! -LocationType folder -LocationPath $(pwd)
