version: 2
jobs:
  build:
    docker:
      - image: vlecerf/checkmarx-cli-docker
    steps:
      - checkout
      - run: pwd
      - run: ls -lrt
      - run: /opt/CxConsolePlugin/runCxConsole.sh Scan -verbose -CxServer cd879533.ngrok.io -Projectname "CxServer\testCircleCI" -CxUser jb@cx.com -CxPassword Poiuytrewq1@ -LocationType folder -LocationPath $(pwd)
