version: 2
jobs:
  build:
    docker:
      - image: vlecerf/checkmarx-cli-docker
    steps:
      - checkout
      - run: pwd
      - run: ls -lrt
      #- run: /opt/CxConsolePlugin/runCxConsole.sh Scan -verbose -CxServer yourcheckmarxserver.com -Projectname "CxServer\yourprojectname" -CxUser yourcxusername -CxPassword yourcxpassword -LocationType folder -LocationPath $(pwd)
      #- run: /opt/CxConsolePlugin/runCxConsole.sh Scan -verbose -CxServer yourcheckmarxserver.com -Projectname "CxServer\yourprojectname" -CxToken yourtoken -LocationType folder -LocationPath $(pwd)
      - run: /opt/CxConsolePlugin/runCxConsole.sh Scan -verbose -CxServer cxprivatecloud.checkmarx.net -Projectname "CxServer\SP\EMEA\checkmarx.com-855\testCircleCI" -cxToken token-LocationType folder -LocationPath $(pwd)

